spring:
  graphql:
    graphiql:
      enabled: false
    websocket:
      path: /software/udl/graphql/sg1/graphql
    path: /software/udl/graphql/sg1/graphql
    cache:
      type: redis
      host: localhost
      port: 6371
      redis:
        time-to-live: 60000